language: node_js
node_js:
- 10
before_script:
- npm install -g gulp-cli
script:
- gulp
- npm run coverage
branches:
  only:
  - master
  - develop
cache:
  directories:
  - node_modules
env:
  global:
    secure: ZX78ZuPAGatRczFcrF9wnt/bPtiT92w1+4IYAeaQwMORKgjTHZV6levhLpfFtxZ5DQuYQwB2SqSBJVTjTKbNAbJ5FcY8Bmi/CAad9kfRovjONfda9eXyAEpm72M5O/w3RSIxOMwJ7Nb2Myc8ZGxmsc8rm3KBxYFLr0EiOWRncVB/j4e9O/PIWg34Fxdc+qtqRiWj+UQUpy+GLSKz9Bp42l4fVN1IDA6eBBoWr63nD7WAH3wChEPfbq+OBbD4Xlpadp5vvBdpa/FTW+96G1ZwO2+DQdmhZqFX0EzWh+UMFxbqigSD0+fNLTxjPLF5qNZgLPdaMZJQav0U6BW0rzEc1LI8/A2Pm2bZ0fiFW7fuvPLKJ85Xol9sIaVblO5TsZOrxsrxwqhkQhRdKAXTg45r3xRmKkRrgyWBNycMJPNYWbTTHdNoXPlKm+w0f2ywJtHr44GHMJCcxo7Q4rb21r6La/Sksi6rBHZmWcApWcJOKvKZ/xK5VT+JDcjUy8XNsYbCaBf+DVGRMfKivuxZr8h4RKwqc7e/IqPiZwVwJCL8XLEwrfFWShKQOi8EfzRJNUBXa9l0sxd1/7F9aKrHhSJICuHyfetAEM+Sznu1gdjHTlXs+aWZlSeh/BJ/c4XMIdXWM0Xa3jYIfFoiuTub0CwHT59TNLqfA+VfNKVMgosTgmw=
notifications:
  slack:
    secure: v248Q660oSta5GtSwi8RKimYxe6vldIMLmBqHdhVQKPeAJvAQeRpfLC7DjWRq9avgGIhRnFj/A4f02Gq1jUVhTqW9kj6jKJEX8e7paNEWIBXtdAtwO75xNY1NslJDlQddRsNU34JH3h0zkf5goGpM7yxYcZN8vxF8CNe4/H6RA0ztQRA4C8OYfWvhLxdrstHMDSOxIiUJHu6uscdDrT8rdKkn8htc6D57qs2PmBhbiRtq0WxxMN3mgaByg/4+kt7lX6y2tPu1XRYdC7iRYv7BhHNB++iu7LUgrwYEJWvYxrhI4tiajxaQqAhneADDrIorjljESd14sjt7mTbrHhpy9hAgfhAoT4Ju7eXlnQjsf07Qi6pCsBwoG0199rugFVYqNgcN4ou29JT2v0xrFlNG6RyyGHDW2n6LQ19dQ6yn6KWlubOAbvBsdeX4P8+wH9t1HLlOfpnVvaEKbYYsN50gUVOH33N6//s9RhlNSrPa30lQEKG9RDGYoHF6no+W8VDS/QJEy7LPl/L2d6XssiITbBVQelRAaVNn+PEVIvZdk8WCRefu9a3VMJFfkMMW5PmwXChpDTatVL46BccUA1PKuk+MBxqJ0Bd2EgfmoiTXA9y2GXzPdxGuQluZh4S3mr4AJvnsoLQTLaD5++ou+XebolgCMO6fyRrX2tIEFIwl8U=
deploy:
- provider: npm
  api_key:
    secure: ddiwjur6v0NLy6k8l8aou3bISyfjjw/G8o9W9PPBKd1oUIW1FpeVUUgje495kJtpgw/VrJxNQtef5Y2bscjC7MmVesmql83S4n7X6reF6C9TRj3sjcppqKJjKXiWZj7bbR5dAcXb+ThFcKo4AHiwa/hXKatUAUCOzI+Aomtm9pIZHktSAxe8KSlXRfyHqJtYohRaahq6ku6awJK1cV5jU/1InQY25AwrarMU7ASKRAx9Gjs2vFmhrO6JnwH3YGTIpI2LDSWokEI0UWIw4zPNSvkDyN8NhuUSgOL+ynK5xTLCvWbxRJtoiCAd2IXn1aej6hzCd0sfOh2/CtIR+llikNbdd4ukFO6+CgG/b8uujGTlvSOr+KuRKjy8vqzkrm0DcwY/JWdeBoEJAhZRbmhrAPZ5JGg+0EUrW7IQN+n/UcecfqN93pJRLF8KC0U/R/V/N8KHb3LhrfbYOci7guxPneBBnjoJm6LWKMjv3MUEeld4sybbyGdZcocYoqKL0zCYvaZ/NIJJl3bRNfm2ya+q2rwjid3zAoncbM9nzuFjxbV7UydVrYfn8EL/hkxAG8+6E8ESvX/mcxx56RDTuLV1+SO5p6HPu4EVmWXA6GeI772btZ/HXdZC2TTp77Jz0v/XXZnGMSPBiQpOU0U76UrtL0YPMZu0NghQ5Ol39axOVzs=
  email:
    secure: E4IZdGJUAndxjHhTGuIOAIUgtB9DW1B+528+xq9/fFEb8reMxB7Fkj6J7zBZmD4utBxTZMvAQdp/5W7F8KNCdh+cOdRP9Zuw+tRtmCufMxc/j7fxe9yiDA5CyVbOsHjxdqtp0NXPWLN/91igLNDxJpk9K8ejpljGyzf51k5w9V4f70T3UfNGdjGtuqYaJF1kHUnHJjEAeXr4XwMzInH70TN5pDfuMm48h9NPzPKvDRpIEFVM++IZAEFsRRQ2TN3kCnYZApqIZk/JQ/4tJuaZ+2I3ZhbBuCtMbM10mgCudLmXUS+n/n5ehInFqhaGr2uX00unV+C6Kn4+KFjNR17MyybBhvD8ixtLJhqSAb+oED3nSr0u4tMyflsH9TJadkx9CDF2bmurNRtGlaRWF/TtJXusLE5ElmuO4ix5sbu/0MZ5YfYWDRLw6MAIs5ZwKtsXoSuSFxhtmkuVFGTyJkjgb3cI2YHb545dmUlkXLqYx7jDgsikKPdSqZ1RFDVZ2mV0D8IEKU++/adQp8Lwj1k34STBIjdwwgkIzhgY+IHkSRGzbaqy2FqfNPu57jdmZ5VJcPdCrxgh0ZEHIJ+PW1PbztCeR+BSuIiapHJii38Xz0TpunnISEuJPUFHKQlibGWcqfOiGTmcCyZ4iwSN+bn9FwkYHQ0jR4N0YyeRFqAzjHk=
  on:
    branch: master
