language: node_js
node_js:
- 10
before_script:
- npm install -g gulp-cli
script:
- gulp
- npm run coverage
branches:
  only:
  - master
  - develop
cache:
  directories:
  - node_modules
env:
  global:
    secure: ESIRHLtSBDXs8Uv5Z4va+VLI+dXA/elxX6xdeWDurznLKN0bSkvK7HD/XDl+lPn8VvxO3sLso3UcFUTnz43wH1aQ1dt0IP5Drj8n5+FCxNqZZyL727vUGDHikzpJt5jn9OwPLyzTRNr8DNJmt1j9NaLN0vfk8DNLWZOudz1WJmHfXd+SD5FXw2K66ybRrNBdE9MsuL2gnPwKP/zH3FSi/Ni90nZnUB6XjENqW+VHtLh+brPcHOnXe4WzvTnfFqCIAHUnuHq7vphaEUkGzGpyHFvwMWfS9U7Lie/Joq5L0VSZpX3PT07ovUm9+TlC8D3bOu+SxRoI41nBR+KJ1yNxrE6BxNXH7h4gaq6y1mE75v1RRDRvKlH31fvxqr4ofT1TIxJBwFknrBSbPV1vyiBxXcfd5trIAvFcQ6Xn/KxjQqK1TRvwyKWXYN8BOniyC3sNjLhpaBjwWP58vvkIc16/f3Hxa+1Ei3DmoB9WPPhSjD0a91u+mo80VDz58O0HVnARls1XWnKlUCi0SpzarNMruOpL6T0/3XG0hDrmdZaIUF2jPWjb8+Zwx6zMbNVSANGXv4c8mmkRPJlt6fV+5aEBVbLRXvnJPSdZJZYS+mYD2oclE9CQp0Wd0zwVuKKdu2NCLXVD0sFhItktTaPrONgBb1wz7i9gZl5hvKqJsHPzb8Q=
notifications:
  slack:
    secure: gsBkwGicUXKRrvj4Yw5+UMBJrNkY37xOp75bNm+Ec7aNb1BDF+WwY7oYIJm+cFEttz1J7JLwg2tIqqaDwI69bqfHiSOgJLQCoRO+ijpKWNSrlBHvuF459i/5voWi2LJCbvlY1kGwYv7K11bcCOHb/2wagnCJucTnu84NbvyTwHWpuhSkxrRU/VxMtQ98upjyVbr2nbSTatZtitXzQ5Orh/S94w/+BG/6RvtBFzQAdmmkCDBp860aKQxTPKhXjIHZl1Z5H3fFcgzZx4D74MdghlaVA7QB2M/GwOcbwJ5OBX7LmI38KwMcvEKq2ZVp3pDbJEhXPKRRnRMi7DPct2kkT00zqa5/FQznWh7UEQM4uRbb50AXhnEFfppAyZUlK2TWc4ePmIXOGbjSMWXkgn7A7gkSXmhQDXMl5OVUO3gWfL2KTKKZEf8sBIIywTDUsLgwMIM55jl4hHzYuw+gBE/DmjjZFGk/lfqZlPVqU1Xl/7Zfx1JTh1oclZ9lB8RjcGIGJ16kf62saVc0k+SoHiDKT6itnPVIHDpRmff3pKZ1byyK0hcdyouJBL0rxvIZb/NlJ/+UDa5QScYf5S+8jFk1Xv5yoRLXgC7UJl0AYmMoErQRco04CEsO91K06LUeCCyOxZm3d60GeVc/33uE/rMZ3PZDg4wcV7us6ok7amG52ws=
deploy:
- provider: npm
  api_key:
    secure: tpoGc/vhtd2LyPnaENy9AHb3Zs2xpa38Sg0mcr8cpuGej4OiSXagDdd08JtAKIHIHO01FdtHR6ub5bAFizxOkigOGBp3UTZqeT5+uSlxFnS7LGNzPCEhWRzibhHXU8BiIkUGwCBA9kB3X6CDnSjq8xE37tqseluucnxMPypcOaqL54BxLGqaPPVP+7anOlE3tVdPE9Y9icZdIZZ7JdKZdCK+SQKoMSZEqfer8ZPOAVEz8nhmpK+Fsc5Uqn91wLkrr7f0muytWTHn6E4AsfYIvlGItzXG6a3WCTst8wEKitGguwPYIBFahy3RLnB/bO5frcLvoRsOZY7KCg/EtC9N15liRKNabWH0Ec6Dj1Mnf0hr5UJ+Be6M5w5TqtawTQJqCOQCnsqJzC17CADB/2zxZuZkvrc5r/hl7855dWC2sw4OdjHDm0Qf0lkar2Veg4GlYcqzgqqGcAFbo53GU+VOsuN8Cqz93LjGc0AiMsQVNiTRzdKREGQxMb07CeIgWsDHW9s3PqzVBJ2MdwoysbnIPOFLrQ9g1vMV6XAmBDVC4Qfptde4X0FgdW804ijQ07iZM+ekA35qp/vI6Au8lj0H3AGFSZm2Ub+7lBVUoIYrxuZDA38XmgDPkxrOTY//OSDjtW/vREttdNBxIsOr2AyippS/Q88tdAN9ibo6k58vTrQ=
  email:
    secure: w2vy872zqFxf6Gm0vqyGneAlaCtfPakiRCq+rlM0LdmG1ZWz0r67y/E9tlZy9UKbuFEKbM+SF7fyN5bgEfACGwuyc2H0HjSZMQHtqQQ3JQsIDyqWOyHjPPJ0IuKL+elglRWTYVEEGPO6b/gBXzqliZacCOqGIPDfbmMHt52RUCa4hWFOYNxKOMk7lJ+V+UEQNx0M9XH6uGfEgubD7G+18ccBuM7lA0pRhOqncIBBNo5+LpmJpm6cKGbDwjmBktjg5t0gIRwpWGY0NVwMhTNtwCSVOr8nsA8M7lL9wAtknKxVSJg/uupDBGSjlOtRRbzM5dvn78a7RS5GO+LFyyDD0qeQRtDOukqiuznbvC5MlW4gOOeZdw45Ps/9eg1Lg4kpxvPNL53XZ8p1HU8tOPuh56TtlNLTgD6VvIbsKerBpUF+YNKSMGWivIxenvPRtx5rZgTueDG3et61OFXogliaWLN8is61XjIUJaatNHyPoLrPDu9aX3FG1Lrfeq/Ztm02R3VccFAtqHjV6Y5AHqbF2HU7hPcGxZJDArFlAXueyORd9CpKq7ziE1KjUT4uwBzutWG7sNKb696GVDymJdFV5AUSllY/khyp438mTxuQPkE4P1DaSwhzylzcM7E6QvrM0RnrIveDFIqC1lnYG1f8VW/W5jMA6MT9hsr7GDFgYHg=
  on:
    branch: master
